layoutdir = "themes/hugo-academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://yanglab.netlify.com/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Dong-Lei Yang lab"
math = true
copyright = "&copy; YangDL Lab 2018 -- all rights reserved"
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Dong-Lei Yang"
  email = "dlyang@njau.edu.cn"
  phone = "20684520"
  address = "No.1 Weigang, Nanjing, China"

  slogan = "Laboratory of Plant Disease Resistance and Epidemiology"
  slogan_text = "YangDL Lab, Nanjing Agricultural University"

  [params.logo]
    image = "img/logo.png"
    link = "http://www.njau.edu.cn/"

#  [[params.navbar_hierarchy]]
#    name = "YangDL Lab"
#    link = "https://yanglab.netlify.com/"
#    position = 1

  [[params.slogan_columns]]
    title = ""
    text = ""
 #   link = "/approach"
 #   link_text = "Read more"
    weight = 1
 #   weight = 3
  
  [[params.slogan_columns]]
    title = ""
    text =  "Xue-Song Liu lab study the fundamental difference between cancer cell and normal somatic cell. With a purpose to identify cancer specific biomarkers and therapeutic targets. Multiple approaches, including cell biochemistry, bioinformatics and mouse modeling, are combined to investigate the basic mechanisms in cancer."
    link = "/research"
    link_text = "Read more"
    weight = 2
  
 # [[params.slogan_columns]]
 #   title = "Mission"
 #   text = "Per peterem ex, Eurystheus videt maeonis, Paeonis uritur. Dextera [legem](http://nubibus.net/qualisardeat), contigerat optabile undis bene: abis sperato. Instrumenta arma, subiectas generis non ipsa patres quia magna Messeneque lacrimaeque torva. Aequo crescunt inrequieta feras, diu illa est occupat aequoribus hunc Elpenora tollens vult robore. Finiat priora vulnere nec Nelei fit quae totidemque intibaque iter longo."
 #   link = "/mission"
 #   link_text = "Read more"
 #   weight = 2



  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 5
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Teaching"
    subtitle = ""
    count = 3
    str_all = "More Classes"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1


  [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 2

  [[menu.main]]
      name = "Projects"
      url = "#projects"
      weight = 3

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 4
  [[menu.main]]
      name = "Teaching"
      url = "#vacancies"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "#posts"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 7
      
params:
  description: "A little bit of data, and me"
  footer: "&copy; [wang zhen](/) | 2018 - 至今 | [My academic website](https://wangzhen.netlify.com/) | [Weibo](https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=2&tn=baiduhome_pg&wd=%E6%83%B3%E8%A6%81%E5%90%97%EF%BC%9F%EF%BC%9F%E5%B0%B1%E4%B8%8D%E7%BB%99&rsv_spt=1&oq=%25E4%25BB%25A5%25E5%2590%258E%25E5%2586%258D%25E5%258A%25A0&rsv_pq=f43228d800031716&rsv_t=56098grRppV%2BhDXEho3rrd%2BKJxhgi7r%2BwbVlt%2F3U6Ngh8lTzSdZzYYQ%2BYXAWTYzfPDTr&rqlang=cn&rsv_enter=1&rsv_sug3=33&rsv_sug1=21&rsv_sug7=100&rsv_sug2=0&inputT=9734&rsv_sug4=9735) "
  disqusURL: "https://www.biowz.info/"
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]
  githubContentURL: "https://github.com/horticulture-kid/biowz/tree/master/content/"
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "https://img.etsystatic.com/il/503467/1545371137/il_570xN.1545371137_cmol.jpg?version=0"
      url: "/"
      alt: "wang zhen"
      tag: ""

  author:
    en: "wang zhen"
    cn: ""



blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
    hrefTargetBlank: true  #这一个没有写的话会默认同一标签栏跳转到目标网页，
    #加上这个就会在新标签打开。至少现在测试在首页是这样
    #参考：https://github.com/leovan/leovan.me  文件：config.*